option('sysconfdir', type: 'string', value: '/etc', description: 'Directory for configuration files like mydns.conf')
option('enable-mysql', type : 'boolean', value : false, description : 'Enable MySQL support (requires mysqlclient headers/libs)')
option('enable-pgsql', type : 'boolean', value : false, description : 'Enable PostgreSQL support (requires libpq headers/libs)')
option('with-openssl', type : 'boolean', value : true, description : 'Build with OpenSSL support')
option('enable-alias', type : 'boolean', value : false, description : 'Enable David Phillips aliasing (sets ENABLE_ALIAS)')
option('enable-static-build', type : 'boolean', value : false, description : 'Build static binary (sets ENABLE_STATIC_BUILD)')
option('enable-profiling', type : 'boolean', value : false, description : 'Enable profiling (-pg, sets ENABLE_PROFILING)')
option('enable-debug', type : 'boolean', value : false, description : 'Enable debugging (-g -DDEBUG, sets ENABLE_DEBUG)')
option('enable-valgrind', type : 'boolean', value : false, description : 'Compile with Valgrind-friendly flags (-DVALGRIND -g, sets ENABLE_VALGRIND)')
option('enable-strict', type : 'boolean', value : false, description : 'Compile with extra-strict warnings (sets ENABLE_STRICT)')
option('enable-status', type : 'boolean', value : true, description : 'Enable the STATUS opcode to check server status (sets ENABLE_STATUS)')
option('disable-date-logging', type : 'boolean', value : false, description : 'Disable date/time in verbose output (sets DISABLE_DATE_LOGGING)')
option('internal_gettext', type : 'boolean', value : false, description : 'Build and use internal gettext library if system libintl is not found.')
